### ISSUE TITLE
Update Release Process for Open Sourced EWC

### ISSUE THREAD

**Issue by arm4b** [StackStorm/st2cd#438]
Due to historical reasons, the Release Automation Workflows in this repo include both StackStorm OSS and EWC Enterprise.

As Extreme Networks open-sourced the EWC Enterprise (https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/), we'll need to cleanup and rework all the automation and workflows to make them actual with the new environment.

While the description looks clear enough, this may be one of the rabbit holes in the [EWC OpenSource](https://github.com/orgs/StackStorm/projects/14) plan.

**Comment by arm4b** [comment]
Per @m4dcoder call, there are Workflows that need to be modified to test the LDAP/RBAC functionality:
https://github.com/StackStorm/st2cd/blob/master/actions/workflows/st2_enterprise_tests.yaml and others.

Additionally, in `st2` repository https://github.com/StackStorm/st2/blob/e5131b8921a5fac27307c0cd292bcfa99a56ba31/requirements.txt#L20-L21 needs to be modified to use the branch like `3.3`, `3.2`, instead of `master` for each release.

The automation for branch creation is already in place:
- https://github.com/stackstorm/st2-rbac-backend/tree/v3.2
- https://github.com/StackStorm/st2-auth-ldap/tree/v3.2

**Comment by blag** [comment]
Status update: this was partially completed in #451.

## Done ##

The `st2_enterprise_tests` action was removed in #451.

* [x] The [`verify_stanley_ssh_key_is_generated_and_installed`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L6) test is obsolete since previous tests will fail if the `stanley` key is not installed.
* [x] The [`verify_rbac_is_enabled`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L16) test is partially obsolete since it checks for `rbac.backend = enterprise` which doesn't work anymore.
* [x] The [`verify_flow_is_installed`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L46) and [`verify_flow_is_available`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L56) tests are obsolete, since st2flow is now fully integrated into st2web.
* [x] The [`verify_ldap_auth_backend_is_installed`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L66) test is obsolete, since the LDAP backend is now installed, but not configured, by default with at least the one-line install script.
* [x] The [`verify_enterprise_rbac_backend_is_installed`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L77) test is obsolete, since the RBAC backend is now installed, but not configured, by default with at least the one-line install script.

## Still To Do ##

* [ ] We should enable and configure LDAP at some point as part of our end-to-end test suite.
  - [ ] Need to spin up an LDAP server, or at least a mock LDAP server in our AWS infrastructure.
* [ ] We should enable and configure RBAC at some point as part of our end-to-end test suite.
  - [ ] The [`verify_rbac_is_enabled`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L16) test from `st2_enterprise_tests` should still check for `rbac.enabled = true`.
  - [ ] The [`verify_default_rbac_admin_role_assignments_are_present`](https://github.com/StackStorm/st2cd/pull/451/files#diff-f973f498b17b234eaf09b73e23ccdae4defa736a7bb750a062cf60fa69eeb940L37) test should still check that the built-in `admin` and `st2admin` users still exist.
    + [ ] I don't think RBAC assignment files are created anymore, so the [actions/scripts/verify_default_rbac_admin_role_assignments_are_present.sh](https://github.com/StackStorm/st2cd/pull/451/files#diff-9846f2ab63316f377f983c8dab7257e13be6558f36033dc4eaf6585a90d2ade4) script needs to be rescued and updated.
  - [ ] We should also test the LDAP mappings and custom roles for the RBAC backend in our end-to-end tests. This relies on having the LDAP backend enabled as well, so it's also dependent on some sort of LDAP server being available in the end-to-end testing environment.
* [ ] As you noted, the automation around branch creation for st2-rbac-backend and st2-auth-ldap has been implemented, and we still need to add some automation to use those branches in the requirements files in the st2 repository during release. Unfortunately I don't think we have a good example/template for this process, so implementing this might be an involved process.
